# Headless service for geo-replication api nodes.
# It is used for mysql cluster internal communications.
{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "mgm.pdb" . }}
  labels:
    {{- include "labels.commonlabels" . }}
    {{- range .Values.commonlabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.podDisruptionBudget.labels }}
      {{- range $.Values.podDisruptionBudget.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- range .Values.selector }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
