global:
  imagePullPolicy: IfNotPresent
  # Database conflict resolution. This feature is only available if the daatabase is MySQL cluster (NDB)
  ndbConflictResolutionEnabled: true
  # Docker registry name
  dockerRegistry: docker-registry.openstack.in.oracle.com:5000
  envJaegerAgentHost: ''
  envJaegerAgentPort: 6831
  envMysqlHost: ''
  envMysqlPort: ''
  serviceMeshEnabled: 'false'
  istioSidecarQuitUrl: http://127.0.0.1:15020/quitquitquit
  istioSidecarReadyUrl: http://127.0.0.1:15020/healthz/ready
  nfInstanceId: "NA"
  shutdownGracePeriod:
    app: 30s
  servicePorts:
      pcfSmServiceHttp: 5809
      pcfSmServiceHttps: 5805
      preServiceHttp: 5806
      configServerHttp: 5807
      pcfUserServiceHttp: 5808
      policydsHttp: 8080
      auditServiceHttp: 5807
      bindingHttp: 8080
      cmServiceHttp: 8000
      bulwarkServiceHttp: 8000
  containerPorts:
      monitoringHttp: 9000
      pcfSmServiceHttp: 8080
      pcfSmServiceHttps: 9443
      javaDebugger: 5801
  k8sResource:
    container:
      prefix:
      suffix:
  metricPrefix: 'occnp'
  metricSuffix:
  customExtension:
    allResources:
      labels: {}
      annotations: {}

    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}

    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false

image: occnp/oc-pcf-sm
imageTag: 22.1.0
envHttp2Enabled: 'true'
envMysqlDatabase: occnp_pcf_sm
envDbMaxPoolSize: 32
envDbMinIdleConnections: -1
envJaegerSamplerParam: '1'
envJaegerSamplerType: ratelimiting
envDomainDispatcherQueueSize: 32
envDomainWorkerThreadNumber: 0
nodeSelectorEnabled: false
nodeSelectorKey: zone
nodeSelectorValue: app
envLoggingLevelApp: INFO
defaultBsfApiRoot: ''
envOathAccessTokenNfType: 'true'
auditRequestDelay: 10
auditMaxRequests: 30
altServiceReqTimeout: 3000
altServiceLookupInterval: 3000
altServiceHTTP2Enabled: true
altServiceCachingEnabled: true
envServiceConnectorIdleTimeout: 600000
httpServerConnectionIdleTimeout: 660000
bindingSvcEnabled: 'true'
envUseHttp11ForUserServiceConnection: 'false'
appName: ocpm
useLbLabelsAndAnnotations: false
maxHttp2ClientConnPerDestination: 6
hookRestartPolicy: OnFailure
nrfDiscoveryLocality: null
nrfDiscoveryThreshold: 80
policyServiceRetryCount: 1
enablePdsV2Api: 'true'
bulwarkServiceEnable: 'true'
serverHttpBufferSize: 15360
serverHttpDirectBuffersEnabled: 'true'

timers:
  serverTimeout: 12000
  userServiceConnectorTimeout: 6000
  policyServiceConnectorTimeout: 3000
  bindingServiceConnectorTimeout: 3000
  paServiceConnectorTimeout: 3000
  smServiceConnectorTimeout: 3000
  bsfConnectorTimeout: 3000
  afConnectorTimeout: 3000
  smfConnectorTimeout: 3000
  configConnectionTimeout: 5000
  configReadTimeout: 1000


resources:
  limits:
    ephemeralStorage: 1Gi
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3

minReplicas: 2
maxReplicas: 8
averageCpuUtil: 60

service:
  type: ClusterIP
  port: 0

  customExtension:
    labels: {}
    annotations: {}

deployment:
  customExtension:
    labels: {}
    annotations: {}


fullnameOverride: oc-pcf-sm

dependenciesLogging:
  - name: logging.level.org.springframework
    value: WARN
  - name: logging.level.org.hibernate
    value: WARN
  - name: logging.level.io.undertow
    value: WARN
  - name: logging.level.io.jaegertracing
    value: WARN
  - name: logging.level.com.zaxxer.hikari
    value: WARN

metrics:
  egressLatencyBuckets:
    max: 10
    size: 50
logging:
  burst:
    rate: 750
    max: 3000
  consoleFormat: jsonConsole
  locationInfo: false

extraContainers: USE_GLOBAL_VALUE

probes:
  liveness:
    monitorInterval: 5
    features:
      deadlockDetection: true

cmagent:
  connectTimeout: 1000
  readTimeout: 1000
  maxRetries: 2
  retryInterval: 1000
  pollingInterval: 5000
  nfProfileUri: /pcf/nf-common-component/v1/nrf-client-nfmanagement/nfProfileList

bulwarkService:
  connectTimeout: 3000
  HTTP2Enabled: 'true'

#Db hook Configuration
dbConfig:
  dbEngine: InnoDB
