global:
  pcrfCoreEnable: true
  imagePullPolicy: IfNotPresent
  # Database conflict resolution. This feature is only available if the daatabase is MySQL cluster (NDB)
  ndbConflictResolutionEnabled: true
  # Docker registry name
  dockerRegistry: docker-registry.openstack.in.oracle.com:5000
  envJaegerAgentHost: ''
  bindingSvcEnabled: 'true'
  policydsEnabled: 'true'
  serviceMeshEnabled: 'false'
  nfInstanceId: NA
  istioSidecarQuitUrl: http://127.0.0.1:15020/quitquitquit
  istioSidecarReadyUrl: http://127.0.0.1:15020/healthz/ready
  servicePorts:
      pcrfCoreHttp: 9080
      pcrfCoreDiameter: 3868
      preServiceHttp: 5806
      configServerHttp: 5807
      pcfUserServiceHttp: 5808
      bindingHttp: 8080
      policydsHttp: 8080
  containerPorts:
      monitoringHttp: 9090
      pcrfCoreHttp: 9080
      pcrfCoreDiameter: 3868
      javaDebugger: 5801
  k8sResource:
    container:
      prefix:
      suffix:
  metricPrefix: 'occnp'
  metricSuffix:
  customExtension:
    allResources:
      labels: {}
      annotations: {}

    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}

    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false


image: occnp/oc-pcrf-core
imageTag: 22.1.0
replicas: 2
envLoggingLevelRoot: INFO
envDiameterRealm: ''
envDiameterIdentity: ''
envJaegerSamplerParam: '1'
envJaegerSamplerType: ratelimiting
envJaegerServiceName: pcrf-core
envMysqlDatabase: occnp_pcrf_core
envDbMaxPoolSize: 32
nodeSelectorEnabled: false
nodeSelectorKey: zone
nodeSelectorValue: app
appName: ocpm
useLbLabelsAndAnnotations: false
hookRestartPolicy: OnFailure
auditRequestDelay: 10
auditMaxRequests: 30

minReplicas: 2
maxReplicas: 8
averageCpuUtil: 60

resources:
  limits:
    ephemeralStorage: 2Gi
    cpu: 8
    memory: 2Gi
  requests:
    cpu: 4
    memory: 1Gi

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3

service:
  type: NodePort
  port: 0
  
  customExtension:
    labels: {}
    annotations: {}

deployment:
  customExtension:
    labels: {}
    annotations: {}

fullnameOverride: oc-pcrf-core

dependenciesLogging:
  - name: logging.level.org.springframework
    value: WARN
  - name: logging.level.org.hibernate
    value: WARN
  - name: logging.level.io.undertow
    value: WARN
  - name: logging.level.io.jaegertracing
    value: WARN
  - name: logging.level.com.zaxxer.hikari
    value: WARN

logging:
  burst:
    rate: 750
    max: 3000
  consoleFormat: jsonConsole
  locationInfo: false

extraContainers: USE_GLOBAL_VALUE

#Db hook Configuration
dbConfig:
  dbEngine: InnoDB
