# Copyright 2019 (C), Oracle and/or its affiliates. All rights reserved.

mysql:
  primary:
    host: "ocnssf-mysql"
  secondary:
    host: "ocnssf-mysql"
  port: 3306 

replicaCount: 1

image:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5745

loglevel: "ERROR"
    
nrf:
  subscription: false

notificationHandlerUrl: http://ocnssf-ingress:80

delayedNotificationEnabled: false
notificationDelay: 5000

httpMaxRetries: 3

nfId: 9faf1bbc-6e4a-4454-a507-aef01a101a01

grEnabled: false
commonServiceName: nsconfig
