global:
  imagePullPolicy: IfNotPresent
  dockerRegistry: docker-registry.openstack.in.oracle.com:5000
  serviceMeshEnabled: 'false'
  istioSidecarReadyUrl: http://127.0.0.1:15020/healthz/ready
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  envJaegerAgentHost: ''
  envJaegerAgentPort: 6831
  envMysqlHost: ''
  envMysqlPort: ''
  dbCredSecretName: ''
  envDbMaxLifeTime: 540000
  envDbIdleTimeout: 540000
  servicePorts:
      queryServiceHttp: 5805
      pcfAmServiceHttp: 5904
      bsfManagementServiceHttp: 5903
      pcrfCoreHttp: 9080
      bindingHttp: 8080
      configServerHttp: 5807
      policydsHttp: 8080
  containerPorts:
      monitoringHttp: 9000
      queryServiceHttp: 8081
      javaDebugger: 5801
  k8sResource:
    container:
      prefix:
      suffix:
  customExtension:
    allResources:
      labels: {}
      annotations: {}

    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}

    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false
 
image: occnp/oc-query
imageTag: 22.1.0
enabled: true
envHttp2Enabled: 'false'
replicas: 1
nodeSelectorEnabled: false
nodeSelectorKey: zone
nodeSelectorValue: app
envLoggingLevelApp: INFO
envMysqlDatabaseSmService: 'occnp_pcf_sm'
envMysqlDatabaseUeService: 'occnp_pcf_ue'
appName: ocpm
useLbLabelsAndAnnotations: false
envJaegerSamplerParam: '1'
envJaegerSamplerType: ratelimiting

timers:
  configConnectionTimeout: 5000
  configReadTimeout: 1000

resources:
  limits:
    ephemeralStorage: 1Gi
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3

service:
  type: ClusterIP
  port: 0
  
  customExtension:
    labels: {}
    annotations: {}

deployment:
  customExtension:
    labels: {}
    annotations: {}

fullnameOverride: ocpm-queryservice

dependenciesLogging:
  - name: logging.level.org.springframework
    value: WARN
  - name: logging.level.org.hibernate
    value: WARN
  - name: logging.level.io.undertow
    value: WARN
  - name: logging.level.io.jaegertracing
    value: WARN
  - name: logging.level.com.zaxxer.hikari
    value: WARN
logging:
  burst:
    rate: 750
    max: 3000
  consoleFormat: jsonConsole
  locationInfo: false

extraContainers: USE_GLOBAL_VALUE

probes:
  liveness:
    monitorInterval: 5
    features:
      deadlockDetection: true
