global:
  imagePullPolicy: IfNotPresent
  configServerEnable: true
  dockerRegistry: docker-registry.openstack.in.oracle.com:5000
  serviceMeshEnabled: 'false'
  istioSidecarQuitUrl: http://127.0.0.1:15020/quitquitquit
  istioSidecarReadyUrl: http://127.0.0.1:15020/healthz/ready
  dbCredSecretName: ''
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  envJaegerAgentHost: ''
  envJaegerAgentPort: 6831
  envMysqlHost: ''
  envMysqlPort: ''
  envDbMaxLifeTime: 540000
  envDbIdleTimeout: 540000
  servicePorts:
      configServerHttp: 5807
  containerPorts:
      monitoringHttp: 9000
      configServerHttp: 8001
  configServerFullNameOverride: ocpm-config
  k8sResource:
    container:
      prefix:
      suffix:
  customExtension:
    allResources:
      labels: {}
      annotations: {}

    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}

    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  configFetch:
    maxRetries: 2
    retryInterval: 1000
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false
  tolerations: []
image: occnp/oc-config-server
imageTag: 22.1.0
envMysqlDatabase: occnp_config_server
envLoggingLevelApp: INFO
replicas: 1
tolerations: []
nodeSelectorEnabled: false
nodeSelectorKey: zone
nodeSelectorValue: app
helmBasedConfigurationNodeSelectorApiVersion: "v1"
appName: ocpm
useLbLabelsAndAnnotations: false
envJaegerSamplerParam: '1'
envJaegerSamplerType: ratelimiting
hookRestartPolicy: OnFailure

persistence:
  lock:
    retryLimit: 3
    retryInterval: 1000

resources:
  limits:
    ephemeralStorage: 1Gi
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3

service:
  type: ClusterIP
  port: 0
  customExtension:
    labels: {}
    annotations: {}

deployment:
  customExtension:
    labels: {}
    annotations: {}



dependenciesLogging:
  - name: logging.level.org.springframework
    value: WARN
  - name: logging.level.org.hibernate
    value: WARN
  - name: logging.level.io.undertow
    value: WARN
  - name: logging.level.io.jaegertracing
    value: WARN
  - name: logging.level.com.zaxxer.hikari
    value: WARN
logging:
  burst:
    rate: 750
    max: 3000
  consoleFormat: jsonConsole
  locationInfo: false

extraContainers: USE_GLOBAL_VALUE

probes:
  liveness:
    monitorInterval: 5
    features:
      deadlockDetection: true

#Db hook Configuration
dbConfig:
  dbEngine: InnoDB

