# Copyright 2019 (C), Oracle and/or its affiliates. All rights reserved.

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hp-autoscaler-nsselection
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "nsselection.fullname" . }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.resources.target.averageCpuUtil }}
---
apiVersion: v1
kind: Service
metadata: 
  name: {{ template "nsselection.fullname" . }}
  labels:
    {{- include "labels.nonlbServices" . }}
    io.kompose.service: {{ template "nsselection.fullname" . }}
    category: nssf
  annotations:
    {{- include "annotations.nonlbServices" . }}
spec:
  ports:
  - port: {{ .Values.global.nsselection.portConfiguration.servicePort }}
    targetPort: {{ .Values.global.nsselection.portConfiguration.containerPort }}
    name: http2
  selector:
    app.kubernetes.io/name: {{ template "chart.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    io.kompose.service: {{ template "nsselection.fullname" . }}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nsselection.fullname" . }}
  labels:
    {{- include "labels.nonlbDeployments" . }}
    io.kompose.service: {{ template "nsselection.fullname" . }}
  annotations:
    {{- include "annotations.nonlbDeployments" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      io.kompose.service: {{ template "nsselection.fullname" . }}
  template: #create pods using pod definition in this template
    metadata:
      annotations:
        {{- include "annotations.nonlbDeployments" . | indent 4 }}
        prometheus.io/port: "{{ .Values.global.nsselection.portConfiguration.commonServicePort }}"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/scrape: "true"
        oracle.com/cnc: "true"
      labels:
        {{- include "labels.nonlbDeployments" . | indent 4 }}
        io.kompose.service: {{ template "nsselection.fullname" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - {{ template "nsselection.fullname" . }}
              topologyKey: "kubernetes.io/hostname"
      containers:
      {{- include "extraContainers" . | nindent 6}}
      - name: {{ template "container.fullname" . }}
        image: "{{ .Values.global.dockerRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullpolicy }}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.global.nsselection.portConfiguration.commonServicePort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.global.nsselection.portConfiguration.commonServicePort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

        ports:
        - containerPort: {{ .Values.global.nsselection.portConfiguration.containerPort }}
          name: http2-sig
        - containerPort: {{ .Values.global.nsselection.portConfiguration.commonServicePort }}
          name: cnc-metrics
        env:
        - name: SERVER_PORT
          value: "{{ .Values.global.nsselection.portConfiguration.servicePort }}"
        - name: CONTAINER_PORT
          value: "{{ .Values.global.nsselection.portConfiguration.containerPort }}"
        - name: COMMON_SERVICE_PORT
          value: "{{ .Values.global.nsselection.portConfiguration.commonServicePort }}"
        - name: MYSQL_PRIMARY_HOST
          value: "{{ .Values.global.mysql.primary.host }}"
        - name: MYSQL_SECONDARY_HOST
          value: "{{ .Values.global.mysql.secondary.host }}"
        - name: MYSQL_PORT
          value: "{{ .Values.global.mysql.port }}"
        - name: DATABASE_SECRETKEY_NAME
          value: "{{ .Values.global.appDbCredSecretName }}"
        - name: DATABASE_SECRETKEY_NAMESPACE
          value: "{{ .Values.global.nameSpace }}"
        - name: NF_ID
          value: "{{ .Values.global.nfInstanceId }}"
        - name: NRF_PRIMARY_HOST_URL
          value: "{{ .Values.nrf.primaryUrl }}"
        - name: INDIRECT_COMMUNICATION_SUPPORT_ENABLE
          value: "{{ .Values.global.indirectCommunicationSupportEnable }}"
        - name: NSSF_API_ROOT
          value: "{{ .Values.global.nssfApiRoot }}"
        - name: NF_SET
          value: "{{ .Values.global.nfSet }}"
        - name: SUPPORTED_PLMN_LIST
          value: "{{ .Values.global.supportedPlmnList }}"
        - name: NRF_SECONDARY_HOST_URL
          value: "{{ .Values.nrf.secondaryUrl }}"
        - name: PROVISON_DATABASE_NAME
          value: "{{ .Values.global.provisionDbName }}"
        - name: STATE_DATABASE_NAME
          value: "{{ .Values.global.stateDbName }}"
        - name: spring.datasource.statedb.jdbc-url
          value: jdbc:mysql://{{ .Values.global.mysql.primary.host }}:{{ .Values.global.mysql.port }},{{ .Values.global.mysql.secondary.host }}:{{ .Values.global.mysql.port }}/{{ .Values.global.stateDbName }}?failOverReadOnly=false&createDatabaseIfNotExist=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        - name: spring.datasource.statedb.username
          valueFrom:
           secretKeyRef:
            name: "{{ .Values.global.appDbCredSecretName }}"
            key: mysql-username
        - name: spring.datasource.statedb.password
          valueFrom:
           secretKeyRef:
            name: "{{ .Values.global.appDbCredSecretName }}"
            key: mysql-password
        - name: spring.datasource.provisondb.jdbc-url
          value: jdbc:mysql://{{ .Values.global.mysql.primary.host }}:{{ .Values.global.mysql.port }},{{ .Values.global.mysql.secondary.host }}:{{ .Values.global.mysql.port }}/{{ .Values.global.provisionDbName }}?failOverReadOnly=false&createDatabaseIfNotExist=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        - name: spring.datasource.provisondb.username
          valueFrom:
           secretKeyRef:
            name: "{{ .Values.global.appDbCredSecretName }}"
            key: mysql-username
        - name: spring.datasource.provisondb.password
          valueFrom:
           secretKeyRef:
            name: "{{ .Values.global.appDbCredSecretName }}"
            key: mysql-password
        - name: LOGGING_LEVEL
          value: "{{ .Values.loglevel }}"
        - name: USE_NRF_DISC
          value: "{{ .Values.features.nrfdiscovery }}"
        - name: AMF_TIME
          value: "{{ .Values.reqnftime }}"
        - name: NSSF_OUTBOUND_PROXY
          value: "{{ .Values.outboundProxy }}"
        - name: RELEVANCE_FEATURE_ENABLED
          value: "{{ .Values.features.relevance }}"
        - name: NRF_CLIENT_NFDISCOVERY_URL
          value: "http://{{ .Release.Name }}-{{ .Values.global.nfName }}-nrf-client-nfdiscovery:{{ .Values.global.discoveryServicePort }}"
        - name: NRF_QUERY_LIMIT
          value: "{{ .Values.nrfDiscoveryProperties.disclimit }}"
        - name: CANDIDATE_LIST_LIMIT
          value: "{{ .Values.candidateResolutionProperties.maxcandidates }}"
        - name: RESOLVE_CANDIDATES_FEATURE_ENABLED
          value: "{{ .Values.features.candidateResolution }}"
        - name: APP_NAME
          value: {{ template "ocnssf.name" . }}
        - name: ENG_VERSION
          value: {{ .Chart.Version | quote }}
        - name: APP_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: MICROSERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOME_MCC
          value: "{{ .Values.homeMcc }}"
        - name: HOME_MNC
          value: "{{ .Values.homeMnc }}"
        - name: MAX_RETRIES
          value: "{{ .Values.httpMaxRetries }}"
        - name: HIKARI_POOL_SIZE
          value: "{{ .Values.hikariPoolSize}}"
        - name: IO_THREADS
          value: "{{ .Values.ioThreads}}"
        - name: WORKER_THREADS
          value: "{{ .Values.workerThreads}}"
        - name: CORE_POOL_SIZE
          value: "{{ .Values.corePoolSize}}"
        - name: MAX_POOL_SIZE
          value: "{{ .Values.maxPoolSize}}"
        - name: QUEUE_CAPACITY
          value: "{{ .Values.queueCapacity}}"
        - name: COMMON_CFG_CLIENT_ENABLED
          value: {{ .Values.global.commonCfgClient.enabled | quote }}
        - name: COMMON_CFG_SERVER_HOST
          value: "{{ .Release.Name }}-nsconfig"
        - name: COMMON_CFG_SERVER_PORT
          value: {{ .Values.global.nsconfig.portConfiguration.servicePort | quote }}
        - name: COMMON_CFG_SERVER_POLLING_INTERVAL
          value: {{ .Values.global.commonCfgClient.pollingInterval | quote }}
        - name: MICROSERVICE_NAME_FOR_COMMON_CONFIG
          value: {{ .Values.commonServiceName }}
        - name: FEATURE_NEGOTIATION_ENABLE
          value: "{{ .Values.global.SupportedFeatureNegotiationEnable }}"
        - name: ES3XX_ENABLE
          value: "{{ .Values.global.threegppFeatures.NsSelection.ES3XX }}"
