{{- if $.Values.global.alternateRouteServiceEnable }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "hpautoscalar.fullname" . }}-v1
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ template "alternate-route.fullname" . }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.resources.target.averageCpuUtil }}
{{- end }}
