# Headless service for geo-replication api nodes.
# It is used for mysql cluster internal communications.
{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "dbmonitorsvc-pdb.fullname" . }}
  labels:
    app: {{ template "db-monitor-svc.name" . }}
    chart: {{ template "db-monitor-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "labels.commonlabels" . }}
{{- with .Values.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "db-monitor-svc.name" . }}
      release: {{ .Release.Name }}
{{- end }}
