apiVersion: v1
kind: Service
metadata:
  name: {{ template "dbmonitorsvc-service.fullname" . }}
  labels:
    app: {{ template "db-monitor-svc.name" . }}
    chart: {{ template "db-monitor-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "labels.commonlabels" . }}
{{- with .Values.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.global.useIPv6 }}
  ipFamilyPolicy: {{ .Values.global.services.ipFamilyPolicy }}
  ipFamilies:
      - {{ .Values.global.services.primaryDualStackIpFamily }}
  {{- else }}
  ipFamilyPolicy: {{ .Values.global.services.ipFamilyPolicy }}
  ipFamilies:
      - IPv4
  {{- end }}
  ports:
    - port: {{ .Values.service.statusApiPort }}
      targetPort: http
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol }}
      name: {{ .Values.service.statusApiPortName }}
    - port: {{ .Values.service.actuatorPort }}
      targetPort: metrics
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol }}
      name: {{ .Values.service.actuatorPortName }}
  selector:
    app: {{ template "db-monitor-svc.name" . }}
    release: {{ .Release.Name }}
