global:
  imagePullPolicy: IfNotPresent
  # Database conflict resolution. This feature is only available if the daatabase is MySQL cluster (NDB)
  ndbConflictResolutionEnabled: true
  # Docker registry name
  nfInstanceId: "NA"
  dockerRegistry: docker-registry.openstack.in.oracle.com:5000
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  envJaegerAgentHost: ''
  envJaegerAgentPort: 6831
  envMysqlHost: ''
  envMysqlPort: ''
  serviceMeshEnabled: 'false'
  istioSidecarQuitUrl: http://127.0.0.1:15020/quitquitquit
  istioSidecarReadyUrl: http://127.0.0.1:15020/healthz/ready
  servicePorts:
      pcfAmServiceHttp: 5904
      pcfAmServiceHttps: 5905
      preServiceHttp: 5806
      pcfUserServiceHttp: 5808
      egressGatewayHttp: 8080
      cmServiceHttp: 8000
  containerPorts:
      monitoringHttp: 9000
      pcfAmServiceHttp: 8080
      pcfAmServiceHttps: 9443
      javaDebugger: 5801
  k8sResource:
    container:
      prefix:
      suffix:
  customExtension:
    allResources:
      labels: {}
      annotations: {}
    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}
    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false

image: occnp/oc-pcf-am
imageTag: 22.1.0
envCfgAppId: '18282'
envCfgAppName: amservice
envCfgTopics: system
envHttp2Enabled: 'true'
envMysqlDatabase: pcf_amservice
envDbMaxPoolSize: 32
envDbMinIdleConnections: -1
envDbMaxLifeTime: 540000
envDbIdleTimeout: 300000
envJaegerSamplerParam: '1'
envJaegerSamplerType: ratelimiting
envLoggingLevelApp: INFO
nodeSelectorEnabled: false
nodeSelectorKey: zone
nodeSelectorValue: app
appName: ocpm
useLbLabelsAndAnnotations: false
reqTimeout: 5000
dispatcherThreadPoolSize: 2
httpClientRequestTimeout: 3000
hookRestartPolicy: OnFailure

timers:
  configConnectionTimeout: 5000
  configReadTimeout: 1000

resources:
  limits:
    ephemeralStorage: 1Gi
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3

minReplicas: 2
maxReplicas: 8
averageCpuUtil: 60

service:
  type: ClusterIP
  port: 0
  customExtension:
    labels: {}
    annotations: {}
deployment:
  customExtension:
    labels: {}
    annotations: {}

fullnameOverride: oc-pcf-am

metrics:
  egressLatencyBuckets:
    max: 10
    size: 50

audit:
  maxRequests: 30
  action: NOTIFY
  requestDelay: 10
  auditMode: CONTINUOUS

dependenciesLogging:
  - name: logging.level.org.springframework
    value: WARN
  - name: logging.level.org.hibernate
    value: WARN
  - name: logging.level.io.undertow
    value: WARN
  - name: logging.level.io.jaegertracing
    value: ERROR
  - name: logging.level.com.zaxxer.hikari
    value: WARN
logging:
  burst:
    rate: 750
    max: 3000
  consoleFormat: jsonConsole
  locationInfo: false

extraContainers: USE_GLOBAL_VALUE

probes:
  liveness:
    monitorInterval: 5
    features:
      deadlockDetection: true

cmagent:
  connectTimeout: 1000
  readTimeout: 1000
  maxRetries: 2
  retryInterval: 1000
  pollingInterval: 5000
  nfProfileUri: /pcf/nf-common-component/v1/nrf-client-nfmanagement/nfProfileList

#Db hook Configuration
dbConfig:
  dbEngine: InnoDB
