{{- if .Values.global.bulwarkServiceEnable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: {{ .Values.global.containerPorts.bulwarkServiceDistCache | quote }}
    traffic.sidecar.istio.io/excludeInboundPorts: {{ .Values.global.containerPorts.bulwarkServiceDistCache | quote }}
    {{- include "annotations.deployments" . }}
  labels:
    {{- include "labels.deployments" . }}      
    io.kompose.service: {{ template "bulwarkservice-deployment-name" . }}
  name: {{ template "bulwarkservice-deployment-name" . }}
spec:
  replicas: {{ .Values.minReplicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: {{ template "bulwarkservice-deployment-name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      annotations:
        {{- include "annotations.deployments" . | indent 4 }}
        traffic.sidecar.istio.io/excludeOutboundPorts: {{ .Values.global.containerPorts.bulwarkServiceDistCache | quote }}
        traffic.sidecar.istio.io/excludeInboundPorts: {{ .Values.global.containerPorts.bulwarkServiceDistCache | quote }}
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: {{ .Values.global.containerPorts.monitoringHttp | quote }}
        prometheus.io/scrape: 'true'
      labels:
        {{- include "labels.deployments" . | indent 4 }}      
        io.kompose.service: {{ template "bulwarkservice-deployment-name" . }}
    spec:

      containers:
      - env:
        - name: JAVA_OPTS
        - name: CFG_SERVER_HOST
          value: {{ template "service-name-config-server" . }}
        - name: CFG_SERVER_PORT
          value: {{ .Values.global.servicePorts.configServerHttp | quote }}
        - name: CONNECT_RETRY_MAX
          value: {{ .Values.global.configFetch.maxRetries | quote }}
        - name: CONNECT_RETRY_INTERVAL
          value: {{ .Values.global.configFetch.retryInterval | quote }}
        - name: JAEGER_AGENT_HOST
          value: {{ .Values.global.envJaegerAgentHost | quote }}
        - name: JAEGER_AGENT_PORT
          value: {{ .Values.global.envJaegerAgentPort | quote }}
        - name: JAEGER_SAMPLER_PARAM
          value: {{ .Values.envJaegerSamplerParam | quote }}
        - name: JAEGER_SAMPLER_TYPE
          value: {{ .Values.envJaegerSamplerType | quote }}
        - name: JAEGER_SERVICE_NAME
          value: {{ template "bulwarkservice-deployment-name" . }}
        - name: LOGGING_LEVEL_APP
          value: {{ .Values.envLoggingLevelApp | quote }}
        - name: logging.level.Coherence
        - name: logging.level.com.oracle.coherence
        - name: SERVICE_MESH_CHECK
          value: {{ .Values.global.serviceMeshEnabled | quote }}
        - name: ISTIO_SIDECAR_QUIT_URL
          value: {{ .Values.global.istioSidecarQuitUrl }}
        - name: ISTIO_SIDECAR_READY_URL
          value: {{ .Values.global.istioSidecarReadyUrl }}
        - name: APPLICATION_NAME
          value: {{ .Values.appName | quote }}
        - name: MICROSERVICE_NAME
          value: {{ template "bulwark-service.fullname" .}}
        - name: ENGINEERING_VERSION
          value: {{ .Chart.Version | quote }}
        - name: MARKETING_VERSION
          value: {{ .Chart.AppVersion | quote }}
        {{- range $logger := .Values.dependenciesLogging }}
        - name: {{ $logger.name | quote }}
          value: {{ $logger.value | quote }}
        {{- end }}
        - name: LOG4J2_BURST_RATE
          value: {{ .Values.logging.burst.rate | quote }}
        - name: LOG4J2_BURST_MAX
          value: {{ .Values.logging.burst.max | quote }}
        - name: LOG4J2_LOCATION_INFO
          value: {{ .Values.logging.locationInfo | quote }}
        - name: LOG4J2_CONSOLE_FORMAT
          value: {{ .Values.logging.consoleFormat | quote }}
        - name: COHERENCE_HEADLESS_SERVICE_NAME
          value: {{ template "service-name-bulwark-service-coherence-headless" . }}
        - name: DIST_CACHE_PORT
          value: {{ .Values.global.containerPorts.bulwarkServiceDistCache | quote }}
        - name: MONITORING_PORT
          value: {{ .Values.global.containerPorts.monitoringHttp | quote }}
        - name: SIGNALING_PORT
          value: {{ .Values.global.containerPorts.bulwarkServiceHttp | quote }}
        - name: JAVA_DEBUGGER_PORT
          value: {{ .Values.global.containerPorts.javaDebugger | quote }}
        - name: HTTP_SERVER_CONNECTION_IDLE_TIMEOUT
          value: {{ .Values.httpServerConnectionIdleTimeout | quote }}
        - name: BULWARK_API_ROOT
          value: "http://{{ template "service-name-bulwark" . }}:{{ .Values.global.servicePorts.bulwarkServiceHttp }}"
        {{- if .Values.imageTag }}
        image: "{{ .Values.global.dockerRegistry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
        {{- else }}
        image: "{{ .Values.global.dockerRegistry }}/{{ .Values.image }}:{{ .Values.global.imageTag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: {{ template "container.fullname" . }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.global.containerPorts.monitoringHttp }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.global.containerPorts.monitoringHttp }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        ports:
          - containerPort: {{ .Values.global.containerPorts.bulwarkServiceHttp }}
            protocol: TCP
          - name: distcacheport
            containerPort: {{ .Values.global.containerPorts.bulwarkServiceDistCache }}
            protocol: TCP
        resources: 
          limits:
            {{- if ne (add .Values.global.logStorage .Values.global.crictlStorage)  0 }}
            ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage | quote }}
            {{- end }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}
          requests:
            {{- if ne (add .Values.global.logStorage .Values.global.crictlStorage)  0 }}
            ephemeral-storage: {{ template "bulwark-service-ephemeral-storage-request" . }}
            {{- end }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
    {{- include "extraContainers" . | nindent 6}}
    {{- if $.Values.nodeSelectorEnabled }}
      nodeSelector:
        {{ $.Values.nodeSelectorKey }}: {{ $.Values.nodeSelectorValue }}
    {{- end }}
    {{- if $.Values.global.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
    {{- else }}
      serviceAccountName: {{ template "bulwark.serviceaccount" .}}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - {{ template "chart.fullname" .}}
              topologyKey: "kubernetes.io/hostname"

      restartPolicy: Always
      schedulerName: default-scheduler
{{- end }}


