{{- if .Values.global.bulwarkServiceEnable }}
{{- if not  .Values.global.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bulwark.serviceaccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "bulwark.role" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - services
  - pods
  - endpoints
  verbs:
  - get
  - watch
  - list

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "bulwark.rolebinding" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "bulwark.role" .}}
subjects:
  - kind: ServiceAccount
    name: {{template "bulwark.serviceaccount" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

