# Copyright 2019 (C), Oracle and/or its affiliates. All rights reserved.

replicaCount: 1

image:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5745

loglevel: "OFF"

resources:
  limits:
     cpu: 2
     memory: 1Gi
  requests:
    cpu: 0.01
    memory: 256Mi
  target:
    averageCpuUtil: 10

minReplicas: 2
maxReplicas: 12

mysql:
  primary:
    host: "ocnssf-mysql"
  secondary:
    host: "ocnssf-mysql"
  port: 3306

homeMcc: "100"

homeMnc: "101"

httpMaxRetries: 0

features:
  nrfdiscovery: true
  relevance: false
  candidateResolution: true

nrfDiscoveryProperties:
  disclimit: 240

candidateResolutionProperties:
  maxcandidates: 10

reqnftime: false

outboundProxy: disabled

nrf:
  primaryUrl: http://ocnrf-ambassador.ocnrf-infra:80
  secondaryUrl: http://ocnrf-ambassador.ocnrf-infra:80


hikariPoolSize: 10
ioThreads: 10
workerThreads: 20
commonServiceName: nsselection
