{{ if not  .Values.global.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app.kubernetes.io/component: nrfclient
    app:  {{ template "chart.fullname" . }}
  annotations:
    {{- include "annotations.allResources" . }}
  name:  {{ template "service-prefix" . }}-nrfclient-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "service-prefix" . }}-nrfclient-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "service-prefix" . }}-nrfclient-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app.kubernetes.io/component: nrfclient
    app:  {{ template "chart.fullname" . }}
  annotations:
    {{- include "annotations.allResources" . }}
  name:  {{ template "service-prefix" . }}-nrfclient-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
---


apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app.kubernetes.io/component: nrfclient
    app:  {{template "chart.fullname" .}}
  annotations:
    {{- include "annotations.allResources" . }}
  name:  {{ template "service-prefix" . }}-nrfclient-service-account
{{- end }}
