{{- if and ( $.Values.global.ldapGatewayEnable) (not .Values.global.serviceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "secret-reader-name" . }}
  name: {{ template "secret-reader-name" . }}

rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
{{- end }}
