{{- if and ( $.Values.global.ldapGatewayEnable) (not .Values.global.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "secret-reader-name" . }}
  name: {{ template "secret-reader-name" . }}
{{- end }}
