{{- if and ( $.Values.global.ldapGatewayEnable) (not .Values.global.serviceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "testsa" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  labels:
    app: {{ template "secret-reader-name" . }}
  name: {{ template "secret-reader-name" . }}

subjects:
  - kind: ServiceAccount
    name: {{ template "secret-reader-name" . }}
    namespace: {{ .Release.Namespace }}

roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: {{ template "secret-reader-name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
