{{- if $.Values.global.ldapGatewayEnable }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "annotations.services" . }}
  labels:
    {{- include "labels.services" . }}
    io.kompose.service: {{ template "ldap-gateway-deployment-name" . }}
    category: common
    {{- if not $.Values.global.serviceMeshEnabled }}
    primary-port-name: http2-text
    {{- end }}
  name: {{ template "service-name-ldap-gateway" . }}
spec:
  {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: Cluster
  {{- end }}
  ports:
    - name: http2-text
      port: {{ .Values.global.servicePorts.ldapGatewayHttp }}
      protocol: TCP 
      targetPort: {{ .Values.global.containerPorts.ldapGatewayHttp }}
    - name: https
      port: {{ .Values.global.servicePorts.ldapGatewayHttps }}
      protocol: TCP
      targetPort: {{ .Values.global.containerPorts.ldapGatewayHttps }}
    {{- if .Values.global.exposeObservabilityAtService }}
    - name: {{ .Values.global.cncMetricsName  }}
      port: {{ .Values.global.containerPorts.monitoringHttp }}
      protocol: TCP
    {{- end }}

  selector:
    io.kompose.service: {{ template "ldap-gateway-deployment-name" . }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
  {{- end }}
