apiVersion: v2
name: occndbtier
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 23.2.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 23.2.1.0.0

# Making the db replication service optional if only single site is installed.

dependencies:
  - name: mgm
    version: 23.2.1
    condition: true
  - name: ndb
    version: 23.2.1
    condition: true
  - name: api
    version: 23.2.1
    condition: true
  - name: db-backup-manager-svc
    version: 23.2.1
    condition: db-backup-manager-svc.enabled
  - name: db-monitor-svc
    version: 23.2.1
    condition: true
  - name: db-replication-svc
    version: 23.2.1
    condition: db-replication-svc.enabled

