global:
  bindingSvcEnabled: true
  imagePullPolicy: IfNotPresent
  # Database conflict resolution. This feature is only available if the daatabase is MySQL cluster (NDB)
  ndbConflictResolutionEnabled: true
  # Docker registry name
  dockerRegistry: docker-registry.openstack.in.oracle.com:5000
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  envJaegerAgentHost: ''
  envJaegerAgentPort: 6831
  serviceMeshEnabled: 'false'
  istioSidecarQuitUrl: http://127.0.0.1:15020/quitquitquit
  istioSidecarReadyUrl: http://127.0.0.1:15020/healthz/ready
  shutdownGracePeriod:
    app: 30s
  servicePorts:
      bindingHttp: 8080
      bindingHttps: 8443
  containerPorts:
      monitoringHttp: 9000
      bindingHttp: 8080
      bindingHttps: 8443
      javaDebugger: 5801
  k8sResource:
    container:
      prefix:
      suffix:
  customExtension:
    allResources:
      labels: {}
      annotations: {}

    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}

    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  configFetch:
    maxRetries: 2
    retryInterval: 1000
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false

image: occnp/oc-binding
imageTag: 22.1.0
replicas: 2
envLoggingLevelRoot: INFO
nodeSelectorEnabled: false
nodeSelectorKey: zone
nrfDiscoveryLocality: null
nrfDiscoveryThreshold: 80
altServiceReqTimeout: 3000
altServiceLookupInterval: 3000
altServiceHTTP2Enabled: true
altServiceCachingEnabled: true
nodeSelectorValue: app
envMysqlDatabase: occnp_binding
envJaegerSamplerParam: '1'
envJaegerSamplerType: ratelimiting
envOathAccessTokenNfType: false
appName: ocpm
useLbLabelsAndAnnotations: false
hookRestartPolicy: OnFailure
httpServerConnectionIdleTimeout: 660000
maxHttp2ClientConnPerDestination: 6
httpClientConnectionIdleTimeout: 600000
defaultIpv6PrefixLength: 64


resources:
  limits:
    ephemeralStorage: 1Gi
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 0.5Gi

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3

minReplicas: 2
maxReplicas: 8

averageCpuUtil: 60

service:
  type: ClusterIP
  port: 0

  customExtension:
    labels: {}
    annotations: {}

deployment:
  customExtension:
    labels: {}
    annotations: {}

fullnameOverride: oc-binding

dependenciesLogging:
  - name: logging.level.org.springframework
    value: WARN
  - name: logging.level.org.hibernate
    value: WARN
  - name: logging.level.io.undertow
    value: WARN
  - name: logging.level.io.jaegertracing
    value: WARN
  - name: logging.level.com.zaxxer.hikari
    value: WARN

metrics:
  egressLatencyBuckets:
    max: 10
    size: 50
logging:
  burst:
    rate: 750
    max: 3000
  consoleFormat: jsonConsole
  locationInfo: false

extraContainers: USE_GLOBAL_VALUE

cmagent:
  connectTimeout: 1000
  readTimeout: 1000
  maxRetries: 2
  retryInterval: 1000
  pollingInterval: 5000
  nfProfileUri: /pcf/nf-common-component/v1/nrf-client-nfmanagement/nfProfileList

#Db hook Configuration
dbConfig:
  dbEngine: InnoDB