# Copyright 2019 (C), Oracle and/or its affiliates. All rights reserved.

replicaCount: 1

mysql:
  primary:
    host: "ocnssf-mysql"
  secondary:
    host: "ocnssf-mysql"
  port: 3306

image:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5745

loglevel: "OFF"
relVersion: "v1"
   
httpMaxRetries: 0

resources:
  limits:
     cpu: 2
     memory: 1Gi
  requests:
    cpu: 0.01
    memory: 256Mi
  target:
    averageCpuUtil: 10

minReplicas: 2
maxReplicas: 12

grEnabled: false
notificationRetryDelay: 3000
oauthTokenRequestEnabled:  true
siteId: "01"
commonServiceName: nssubscription
