apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "annotations.services" . }}
  labels:
    {{- include "labels.services" . }}
    io.kompose.service: {{ template "ocpm-queryservice-deployment-name" . }}
    category: common
  name: {{ template "service-name-query" . }}
spec:
  ports:
    - name: http-signaling
      port: {{ .Values.global.servicePorts.queryServiceHttp }}
      protocol: TCP
      targetPort: {{ .Values.global.containerPorts.queryServiceHttp }}
    {{- if .Values.global.exposeObservabilityAtService }}
    - name: {{ .Values.global.cncMetricsName  }}
      port: {{ .Values.global.containerPorts.monitoringHttp }}
      protocol: TCP
    {{- end }}

  selector:
    io.kompose.service: {{ template "ocpm-queryservice-deployment-name" . }}
  sessionAffinity: None
  type: {{ .Values.service.type }}

