{{- if .Values.global.diamGatewayEnable }}
{{- if not  .Values.global.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "diamGateway.serviceaccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
    "helm.sh/hook": "pre-install,pre-upgrade,post-upgrade"
    "helm.sh/hook-weight": "-15"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "diamGateway.role" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "diamGateway.rolebinding" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "diamGateway.role" .}}
subjects:
  - kind: ServiceAccount
    name: {{template "diamGateway.serviceaccount" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
